export const ADD_COMMENT = 'NEW_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const UPVOTE_COMMENT = 'UPVOTE_COMMENT';
export const DOWNVOTE_COMMENT = 'DOWNVOTE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const REMOVE_COMMENT = 'DELETE_COMMENT';
