import {
  FETCH_CATEGORIES_REQUEST,
  FETCH_CATEGORIES_SUCCESS,
  FETCH_CATEGORIES_FAILURE,
} from './categoryTypes';

import {
  FETCH_POST_REQUEST,
  FETCH_POST_SUCCESS,
  FETCH_POST_FAILURE,

  FETCH_POSTS_REQUEST,
  FETCH_POSTS_SUCCESS,
  FETCH_POSTS_FAILURE,

  REMOVE_POST_REQUEST,
  REMOVE_POST_SUCCESS,
  REMOVE_POST_FAILURE,

  UPVOTE_POST_REQUEST,
  UPVOTE_POST_SUCCESS,
  UPVOTE_POST_FAILURE,

  DOWNVOTE_POST_REQUEST,
  DOWNVOTE_POST_SUCCESS,
  DOWNVOTE_POST_FAILURE,

  NEW_POST_OPEN,
  NEW_POST_REQUEST,
  NEW_POST_SUCCESS,
  NEW_POST_FAILURE,

  EDIT_POST_OPEN,
  EDIT_POST_REQUEST,
  EDIT_POST_SUCCESS,
  EDIT_POST_FAILURE,
} from './postTypes';

import {
  FETCH_COMMENTS_REQUEST,
  FETCH_COMMENTS_SUCCESS,
  FETCH_COMMENTS_FAILURE,

  REMOVE_COMMENT_REQUEST,
  REMOVE_COMMENT_SUCCESS,
  REMOVE_COMMENT_FAILURE,

  UPVOTE_COMMENT_REQUEST,
  UPVOTE_COMMENT_SUCCESS,
  UPVOTE_COMMENT_FAILURE,

  DOWNVOTE_COMMENT_REQUEST,
  DOWNVOTE_COMMENT_SUCCESS,
  DOWNVOTE_COMMENT_FAILURE,

  PUBLISH_COMMENT_REQUEST,
  PUBLISH_COMMENT_FAILURE,
  PUBLISH_COMMENT_SUCCESS,
} from './commentTypes';

export default (state = null, action) => {
  switch (action.type) {
    case FETCH_CATEGORIES_FAILURE:
    case FETCH_POST_FAILURE:
    case FETCH_POSTS_FAILURE:
    case REMOVE_POST_FAILURE:
    case UPVOTE_POST_FAILURE:
    case DOWNVOTE_POST_FAILURE:
    case NEW_POST_FAILURE:
    case EDIT_POST_FAILURE:
    case FETCH_COMMENTS_FAILURE:
    case REMOVE_COMMENT_FAILURE:
    case UPVOTE_COMMENT_FAILURE:
    case DOWNVOTE_COMMENT_FAILURE:
    case PUBLISH_COMMENT_FAILURE: {
      return action.payload.error.message;
    }
    case FETCH_CATEGORIES_REQUEST:
    case FETCH_CATEGORIES_SUCCESS:
    case FETCH_POST_REQUEST:
    case FETCH_POST_SUCCESS:
    case FETCH_POSTS_REQUEST:
    case FETCH_POSTS_SUCCESS:
    case REMOVE_POST_REQUEST:
    case REMOVE_POST_SUCCESS:
    case UPVOTE_POST_REQUEST:
    case UPVOTE_POST_SUCCESS:
    case DOWNVOTE_POST_REQUEST:
    case DOWNVOTE_POST_SUCCESS:
    case NEW_POST_OPEN:
    case NEW_POST_REQUEST:
    case NEW_POST_SUCCESS:
    case EDIT_POST_OPEN:
    case EDIT_POST_REQUEST:
    case EDIT_POST_SUCCESS:
    case FETCH_COMMENTS_REQUEST:
    case FETCH_COMMENTS_SUCCESS:
    case REMOVE_COMMENT_REQUEST:
    case REMOVE_COMMENT_SUCCESS:
    case UPVOTE_COMMENT_REQUEST:
    case UPVOTE_COMMENT_SUCCESS:
    case DOWNVOTE_COMMENT_REQUEST:
    case DOWNVOTE_COMMENT_SUCCESS:
    case PUBLISH_COMMENT_REQUEST:
    case PUBLISH_COMMENT_SUCCESS: {
      return null;
    }
    default: {
      return state;
    }
  }
};
